version: "3"
services:
  datascience-notebook:
      # Refer to https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
      image: jupyter/datascience-notebook # Approximately ~4.78GB in size
      volumes:
        - ./notebooks:/home/jovyan/
      ports:
        - 8888:8888
      container_name: datascience-notebook
